### ISSUE TITLE
Color of the bitmap changing from red to blue ?

### ISSUE THREAD

**Issue by ksyamkrishnan** [Beyka/Android-TiffBitmapFactory#34]
Hi,
Thank you so much for the awesome library. Unfortunately when I tried to get bitmap from a tiff file using `TiffLoader.getBitmap(int dir,int sampleSize)` , but the color of the [bitmap](url) is changed from red to blue. I checked the config it is ARGB_8888. Can you please suggest a solution on this issue?
![screenshot_unifier_20180801-112343](https://user-images.githubusercontent.com/3761060/43503601-a534cb08-957d-11e8-88d4-74e20571d0f9.png)
![screenshot_drive_20180801-112326](https://user-images.githubusercontent.com/3761060/43503604-a56ae774-957d-11e8-9230-e2c6e9df4871.png)

**Comment by Beyka** [comment]
What version do you use? There is no class TiffLoader in library. 
Please, provide code which leads to this result

**Comment by GrayCygnus** [comment]
@ksyamkrishnan perhaps you are swapping red/blue channels, or your image has the channels reversed (BGR instead of RGB). In [`TiffBitmapFactory.Options`](https://github.com/Beyka/Android-TiffBitmapFactory/blob/master/src/main/java/org/beyka/tiffbitmapfactory/TiffBitmapFactory.java#L189) there is one option named [`inSwapRedBlueColors`](https://github.com/Beyka/Android-TiffBitmapFactory/blob/master/src/main/java/org/beyka/tiffbitmapfactory/TiffBitmapFactory.java#L248) that is usually set to false, but perhaps you need or are setting it the other way round.

**Comment by Beyka** [comment]
There was a problem with swapping red and blue colors. It was fixed but for some reason I decided to keep inSwapRedBlueColors option.
Any way in the latest release 0.9.8.7 this problem is solved
